### ISSUE TITLE
DDS FAILED [mipmaps] (80070057)

### ISSUE THREAD

**Issue by Bxaa** [microsoft/DirectXTex#233] opened 2021-04-28 17:31 UTC
(80070057: ???????? ????? ???????.) What code page using? (console app)

texconv.exe -w 256 -h 256 -if linear -sepalpha -f BC2_UNORM -srgb -y "test.dds"  **FAILED** [mipmaps] (80070057) **(should generate max mipmaps possible for current dds size)**
texconv.exe -w 256 -h 256 -m **ANY NUM** -if linear -sepalpha -f BC2_UNORM -srgb -y "test.dds"  **SUCCESS!**

I remember early versions doesn't have some issue

TEST DDS:
https://drive.google.com/file/d/1ryfz08wi8iZBskW2dXffCyr_hdTa3Qxi/view?usp=sharing

UPD:
**-if fant** while resize also  cause error

**Comment by walbourn** [comment] 2021-04-28 20:04
The ``???????? ????? ???????`` text is coming from ``FormatMessage`` and the text in English is "The parameter is incorrect". I'm using ``wprintf`` and I'm not modifying the code-page, so I'm not sure why it didn't print correctly for your locale.

The problem is a bug in ``texconv`` in this particular case.

``-m 0`` for images is 'generate all mips', but in the case of a ``DDS`` file I use what's in the original file. Per below, I set my target mips to 12.

```
DDS c:\temp\test.dds
Flags 00021007: CAPS HEIGHT WIDTH PIXELFORMAT MIPMAPCOUNT
2048 x 2048
Pitch: 0
Mipmap count: 12
Surface flags: 00401008: COMPLEX TEXTURE MIPMAP
PIXELFORMAT: 00000004: FOURCC
FourCC = 861165636 'DXT3'
DXGI_FORMAT_BC2_UNORM
```

Then after the resize, the max possible mips is only 9. 

Using ``-m 9`` would be a good workaround for now. I'll fix up the logic there.

Thanks for the report!

**Comment by Bxaa** [comment] 2021-04-28 21:09
Hi,
You should add this
```
const wchar_t* GetErrorDesc(HRESULT hr)
    {
        static wchar_t desc[1024] = {};
        LPWSTR errorText = nullptr;
        DWORD result = FormatMessageW(FORMAT_MESSAGE_FROM_SYSTEM | FORMAT_MESSAGE_ALLOCATE_BUFFER, nullptr,
            static_cast<DWORD>(hr),
            MAKELANGID(LANG_NEUTRAL, SUBLANG_DEFAULT), reinterpret_cast<LPWSTR>(&errorText), 0, nullptr);
        *desc = 0;
        if (result > 0 && errorText)
        {
            setlocale(LC_ALL, ".1251");  // <----------------THIS!
            swprintf_s(desc, L": %ls", errorText);
            size_t len = wcslen(desc);
            if (len >= 2)
            {
                desc[len - 2] = 0;
                desc[len - 1] = 0;
            }
            if (errorText)
                LocalFree(errorText);
        }
        return desc;
    }
```
Now:
<a href="https://ibb.co/kqTbPxW"><img src="https://i.ibb.co/kqTbPxW/codepage.png" alt="codepage" border="0"></a>
Notice: 
Need test on other systems (tested - win10x64 enterprise russian)
(But i think 1251 will work fine on any system)

**Comment by walbourn** [comment] 2021-04-28 21:18
the mips issue is fixed in [this commit](https://github.com/microsoft/DirectXTex/commit/66ffe6e8820e31b351bc21b78f7f5b5576ef0cb5).

**Comment by Bxaa** [comment] 2021-04-28 21:20
Thx
What about -if fant ?
it not work with resize...

**Comment by walbourn** [comment] 2021-04-28 21:22
It looks like I just need to change the C++ locale on startup: ``std::locale::global(std::locale(""));``

**Comment by Bxaa** [comment] 2021-04-28 21:23
As variant...

**Comment by walbourn** [comment] 2021-04-28 21:34
Locale issue should be fixed in [this commit](https://github.com/microsoft/DirectXTex/commit/1ab21d9900b6a9b583ddef334f695f8575699806)

Can you verify it works?

Thanks!

**Closed by walbourn** 2021-04-28 21:34 UTC
Labels: bug

**Comment by Bxaa** [comment] 2021-04-28 21:43
> Can you verify it works?
Yep, all fine
Thx
