### ISSUE TITLE
Issue with reconstructz not working on vector -1 .. 1 range

### ISSUE THREAD

**Issue by c2aDS** [microsoft/DirectXTex#219] opened 2021-02-19 10:10 UTC
Hi,

I have the same issue as https://github.com/microsoft/DirectXTex/issues/214#issue-794785878 
I have an original normal map that I convert to BC5 using photoshop 3dc plugin.
![original](https://user-images.githubusercontent.com/16100333/108489994-84032880-72a2-11eb-9c95-1334deffc66d.png)

Then I try to convert it back to TGA with reconstructz option using this command line:
texconv -y -ft TGA -swizzle grba -reconstructz -f [R8G8B8A8_UNORM](url) bc5.dds

Note : The swizzle is there to swap back x and y channels due to BC5/photoshop 3dc swapping x and y. this works well.

But the generated blue channel is way too strong as compared to the original map 
![reconstructz](https://user-images.githubusercontent.com/16100333/108490197-c2004c80-72a2-11eb-8ed8-5f466e706b36.png)

I think the issue is that reconstrucz does this float z = sqrt(1 - dot(xy, xy)); on a range between 0..1
But what I need is to do the square root on a vector extracted from the normal map and on a range between -1..1 otherwise the result is false.
The operation should be something like float z = sqrt(1 - dot(xy * 2.0 - 1.0, xy * 2.0 - 1.0)) * 0.5 + 0.5;
If I do this manually I obtain the correct blue channel.

Edit : I also tried with the x2bias option but it didn't change the result

**Comment by walbourn** [comment] 2021-02-22 04:56
Thanks. Can you attach the ``.dds`` file itself that you created in Photoshop?

**Comment by c2aDS** [comment] 2021-02-22 09:29
Here is  the zipped BC5 input texture : [BC5.zip](https://github.com/microsoft/DirectXTex/files/6020903/BC5.zip)

**Comment by walbourn** [comment] 2021-02-24 08:21
Thanks for the report and repro.

``-x2bias`` only does something when changing between format types, but since this is a UNORM to UNORM case, it doesn't do anything.

The problem is indeed the wrong formula when doing ``-reconstructz`` for UNORM formats. Fixed in [this commit](https://github.com/microsoft/DirectXTex/commit/23f1a5d19e755b6f8469f56250101799f968a2fe).

**Closed by walbourn** 2021-02-24 08:21 UTC
Labels: bug, tools

**Comment by c2aDS** [comment] 2021-02-24 16:46
I just tested and it works like a charm now. Thanks a lot for the fix.
